baseURL = 'https://n1cs.pages.dev'
languageCode = 'en-us'
title = 'Blogs | Nirjal Paudel'
theme = 'paper'
author = 'Nirjal Paudel'
paginate = 20

enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
# Google analytics code
googleAnalytics = "G-EW6BB7P3VN"
summaryLength = 20

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[permalinks]
  post = "/blogs/:year/:month/:slug/"

[params]
  # color style
  color = 'gray'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'n1rjal'               # twitter.com/YOUR_TWITTER_ID
  github = 'n1rjal'                 # github.com/YOUR_GITHUB_ID
  instagram = 'n1rjal'           # instagram.com/YOUR_INSTAGRAM_ID
  linkedin = 'nirjalpaudel'             # linkedin.com/in/YOUR_LINKEDIN_ID
  rss = true                                # show rss icon

  # home page profile
  avatar = 'GRAVATAR_EMAIL'                 # gravatar email or image url
  name = 'Nirjal Paudel'
  bio = 'Hello world, I am Nirjal Paudel. I am a software engineer and a tech enthusiast. I love to write about technology, programming, and life.'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  favicon = "favicon.ico"                   # customize the default favicon
