import type { Metadata } from "next";
import { Roboto } from "next/font/google"; // Import Roboto
import "./globals.css";
import "highlight.js/styles/github.css";
import ThemeRegistry from "./ThemeRegistry";
import Sidebar from "../components/Sidebar"; // Import Sidebar

const roboto = Roboto({
  weight: ["300", "400", "500", "700"], // Specify weights to load
  subsets: ["latin"],
  display: "swap", // Optimize font loading
}); // Initialize Roboto

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <ThemeRegistry>
          <Sidebar>{children}</Sidebar>
        </ThemeRegistry>
      </body>
    </html>
  );
}
