name: Update random blogs

on:
  schedule:
    - cron: '0 */6 * * *'  # Schedule to run every 6 hours
  workflow_dispatch:

jobs:
  put-notion-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12.1
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.1
      - name: Install requirements.txt
        run: pip install -r requirements.txt
          
      - name: Update reading list data 
        run: python3 scripts/update_reading_list.py
        env:
          NOTION_DATABASE: ${{ secrets.NOTION_DATABASE }}
          NOTION_SECRET: ${{ secrets.NOTION_SECRET }}
          
      - name: Commit reading list data
        run: |
          git config --global user.name github.actions
          git config --global user.email github-actions@github.com
          git add .
          if ! git diff --cached --quiet; then
              git commit -m "chore: generate new reading list"
              git push
          else
              curl -d {} ${{ secrets.PAGES_WEBHOOK_URL }}
          fi

